### ISSUE TITLE
Peer to Peer  Code Reveiw

### ISSUE THREAD

**Issue by Obote** [VicPeralta/awesomeBooks#3]
Hello @VicPeralta :smiley: 

Great work and effort you have put into this project so far.

### Highlights :+1: 

- Good use of Semantic HTML concepts. :100: 
- Descriptive commit messages. :100: 
- Good implementation of Javascript classes :100: 

**You should know there is always room for improvement. Your long hours of work are very much appreciated. However, the code review process is for improving your code, not for criticizing it**

**Comment by VicPeralta** [comment]
Thank you for your kind comments
